[options]
no_icon_names = true

[general]

[aliases]

[icons]
firefox = ""
KeePassXC = ""
Spotify = ""
Slack = ""
discord = ""
Zathura = ""
libreoffice-writer = ""
libreoffice-calc = ""
libreoffice-impress = ""
